FROM nginx:alpine AS ngi

COPY /sedserver.key /etc/nginx/ssl/sedserver.key
COPY /sedserver.crt /etc/nginx/ssl/sedserver.crt
COPY /dist/frontendAG/ /usr/share/nginx/html
COPY /ngnix.conf /etc/nginx/conf.d/default.conf
# sudo openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout sedserver.key -out sedserver.crt
EXPOSE 3070:80
#test
#FROM node:16-alpine3.11 AS build
#RUN mkdir -p /app
#WORKDIR /app
#COPY package.json /app
#RUN npm install
#COPY . /app
#RUN npm run build
#COPY --from=build /app/dist/ngnix.conf  /etc/nginx/conf.d/default.conf
#COPY --from=build /app/dist/frontendAG /usr/share/nginx/html
# sudo openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout sedserver.key -out sedserver.crt
